### PR TITLE
Fix installer branch workflow

### LINKED ISSUE #385: Installer issues
The installer doesn't seem to be respecting the -b switch. It also doesn't allow you to specify a path with a space but will happily build in that path. Output below

Doesn't use alternate branch
```ps
PS D:\EFT - SPT 3.6.0> .\Installer.exe install -b fix-window-coordinates
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Target EscapeFromTarkov (0.13.1.25206) in D:\EFT - SPT 3.6.0.
>> Try #0 Compilation succeed for master branch.
[SPT-AKI] detected. Please make sure you have run the game at least once before installing the trainer.
SPT-AKI is patching binaries during the first run, and we need to compile against those patched binaries.
If you install this trainer on stock binaries, the game will freeze at the startup screen.
Continue installation (yes I have run the game at least once) ? [y/n] (y): y
Created NLog.EFT.Trainer.dll in D:\EFT - SPT 3.6.0\EscapeFromTarkov_Data\Managed.
Created outline in D:\EFT - SPT 3.6.0\EscapeFromTarkov_Data.
[BepInEx] detected. Creating plugin instead of using NLog configuration.
>> Try #0 Compilation succeed for master branch.
Created aki-efttrainer.dll in D:\EFT - SPT 3.6.0\BepInEx\plugins.
PS D:\EFT - SPT 3.6.0>
```

Doesn't like paths with spaces
```ps
PS D:\EFT - SPT 3.6.0> .\Installer.exe install 'D:\EFT - SPT 3.5.0\' -b fix-window-coordinates
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Error: Illegal characters in path.. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues
PS D:\EFT - SPT 3.6.0>
```

### PR DESCRIPTION
**Pull request by sailro**
Fixes #385 

In fact the way it worked before the `-b branch` parameter was only used for the retry step.

### CODE REVIEW

**Review by solareon — APPROVED** [review]
Added a small fix for the BepInEx plugin build as it didn't switch branches with the -b option. Had the output below, first was pre patch, second post patch

```ps
PS D:\EFT - SPT 3.6.0> .\Installer.exe -b fix-installer-branch
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Target EscapeFromTarkov (0.13.1.25206) in D:\EFT - SPT 3.6.0.
>> Try #0 Compilation succeed for fix-installer-branch branch.
[SPT-AKI] detected. Please make sure you have run the game at least once before installing the trainer.
SPT-AKI is patching binaries during the first run, and we need to compile against those patched binaries.
If you install this trainer on stock binaries, the game will freeze at the startup screen.
Continue installation (yes I have run the game at least once) ? [y/n] (y): y
Created NLog.EFT.Trainer.dll in D:\EFT - SPT 3.6.0\EscapeFromTarkov_Data\Managed.
Created outline in D:\EFT - SPT 3.6.0\EscapeFromTarkov_Data.
[BepInEx] detected. Creating plugin instead of using NLog configuration.
>> Try #0 Compilation succeed for master branch.
Created aki-efttrainer.dll in D:\EFT - SPT 3.6.0\BepInEx\plugins.
PS D:\EFT - SPT 3.6.0> .\Installer.exe -b fix-installer-branch
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Target EscapeFromTarkov (0.13.1.25206) in D:\EFT - SPT 3.6.0.
>> Try #0 Compilation succeed for fix-installer-branch branch.
[SPT-AKI] detected. Please make sure you have run the game at least once before installing the trainer.
SPT-AKI is patching binaries during the first run, and we need to compile against those patched binaries.
If you install this trainer on stock binaries, the game will freeze at the startup screen.
Continue installation (yes I have run the game at least once) ? [y/n] (y): y
Created NLog.EFT.Trainer.dll in D:\EFT - SPT 3.6.0\EscapeFromTarkov_Data\Managed.
Created outline in D:\EFT - SPT 3.6.0\EscapeFromTarkov_Data.
[BepInEx] detected. Creating plugin instead of using NLog configuration.
>> Try #0 Compilation succeed for fix-installer-branch branch.
Created aki-efttrainer.dll in D:\EFT - SPT 3.6.0\BepInEx\plugins.
PS D:\EFT - SPT 3.6.0>
```

**Comment by solareon** [comment]
Still looking into the single/double quote issue when you feed it a path.

**Comment by solareon** [comment]
@sailro It looks like the issue is that when you specify the -b after the path it pulls in all the other stuff as part of the path.

**Comment by sailro** [comment]
the issue with "spaces" is in fact related to the ending slash. When using \` or \" I think it is like using an escaped character for the system.

So we have that in the string:
`"C:\\Battlestate Games\\EFT\""`

It's fixed.

**Comment by solareon** [comment]
I did a little more tinkering with it and it seems to be a powershell specific issue with how it tab autocompletes paths as referenced in [this issue](https://github.com/spectreconsole/spectre.console/issues/416). This trailing slash as powershell builds it causes spectre.console to ingest the whole line after the command into the Path variable.

What spectre.console wants to see
```
.\Installer.exe "D:\EFT - SPT 3.6.0\\" -b fix-installer-branch
```
produces the following Path variable `D:\EFT - SPT 3.6.0`

What powershell defaults to
```
.\Installer.exe "D:\EFT - SPT 3.6.0\" -b fix-installer-branch
```
produces the following Path variable `D:\EFT - SPT 3.6.0" -b fix-installer-branch`

What cmd.exe defaults to
```
Installer.exe "D:\EFT - SPT 3.6.0" -b fix-installer-branch
```
produces the following Path variable `D:\EFT - SPT 3.6.0`


Agree though this is kind of an oddball case and doesn't really impact anyone so we can merge this as the branch fix is what was important.

**Pull request merged**
