### PR TITLE
[WIP] Extract strings

### PR DESCRIPTION
**Pull request by sailro**
It's working when compiling from sources with VS.

Updated the installer (to convert resx to resource, then to embed into the assembly)

### CODE REVIEW

**Comment by solareon** [comment]
I take it that this would be a precursor to allowing localization?

**Comment by sailro** [comment]
> I take it that this would be a precursor to allowing localization?

Yep exactly

**Comment by sailro** [comment]
I think we are all good for now.

Will merge this when I'm back from vacations.

**Comment by solareon** [comment]
Alright. Sounds like a plan. If I get a chance I'll build and do some testing

**Pull request merged**
