### PR TITLE
[WIP] Proto for upcoming spt release 0.15.0.32291

### PR DESCRIPTION
**Pull request by sailro**
We should be good now

### CODE REVIEW

**Comment by sailro** [comment]
I found a way to fix the instant-reveal. The trick is to have a patch-method called before the constructor and forcing `examined=true` so a passthrough inventory controller is used where all the items are known and examined.

image

**Comment by Napayanaya** [comment]
Not working on version 0.15.0.32197

**Comment by solareon** [comment]
> Not working on version 0.15.0.32197

Yes because it is for 0.15.0.32291 which is slightly newer. Have you updated SPT to the latest bleeding edge release?

**Comment by sailro** [comment]
While fixing the Wishlist-tracking, I spotted that they added an option in settings to display a little hideout icon on interesting items when looting:

image

image

And so we have easily access to everything needed to track dynamically all required items to improve the hideout.

I added a new options in `loot`:

image

And boom:

image

**Comment by sailro** [comment]
Added a `spawnhi` command as well, to spawn required hideout items:

ezgif-6-1110b8e351

**Comment by Napayanaya** [comment]
> > Не работает на версии 0.15.0.32197
> 
> Да, потому что это для 0.15.0.32291, которая немного новее. Вы обновили SPT до последней версии?

I play on the pirate version of the game, maybe you can tell where you can download a version of the newer. Thank you!

**Comment by sailro** [comment]
Closing this one (but keeping the branch), the upcoming spt-aki `3.10` is now targeting `0.15.2.32678`

**Pull request closed without merging**
