### PR TITLE
Add `spawnqi` command.

### PR DESCRIPTION
**Pull request by sailro**
Spawn items-to-find in active quests.

This will not spawn location-specific / quest-items like folder 033 etc, but all generic items like batteries, injectors, that you can find everywhere.

https://github.com/user-attachments/assets/5c206d89-e57b-4f54-9c85-dbc35ae945f8

### CODE REVIEW

**Comment by solareon** [comment]
That's nice and cheeky. I presume that it spawns them as found in raid yeah? For the ones that are location specific are those really "items" or more just markers that interact like items?

**Comment by sailro** [comment]
> That's nice and cheeky. I presume that it spawns them as found in raid yeah? For the ones that are location specific are those really "items" or more just markers that interact like items?

Yes exactly they are all marked as "found in raid".

Location-specific ones seem to be items, we can even "spawn" them but they will not render on the screen.

**Comment by sailro** [comment]
Note that this work only with **active** quests and for the "find X in raid" assignments.

**Comment by sailro** [comment]
Exactly, in your case it will not work.

See this one:


It will work for Salewa. Why? Because those `find` instructions will create in-game conditions that we can retrieve.

Remember that you can also spawn ay item with the spawn command. So in your case you can use:

`spawn TOZ-106`
`spawn Module-3M`

**Comment by xlisovGH** [comment]
Hello `sailro`,
can you make sure that when using the `spawn` command for example the `Module-3M` armor so that it does not spawn empty?

**Comment by sailro** [comment]
@xlisovGH see https://github.com/sailro/EscapeFromTarkov-Trainer/pull/570

**Pull request merged**
