### PR TITLE
Refine installer

### PR DESCRIPTION
**Pull request by sailro**
- detect SPT-AKI and display the prompt even before trying to compile (because we will probably fail)
- add `C:\SPT` to the well-known list of installations (SPT-AKI default installation path)
- detect when SPT-AKI was never run, and add another warning given it seems hard to understand :)

### CODE REVIEW

**Review by solareon — APPROVED** [review]
Maybe a good idea to add another check if it's in C:\Battlestate Games\Escape from Tarkov\ which is almost always a live install location

**Comment by sailro** [comment]
> Maybe a good idea to add another check if it's in C:\Battlestate Games\Escape from Tarkov\ which is almost always a live install location

Indeed but we should be good for that, we are reading te BST-installer registry:
https://github.com/sailro/EscapeFromTarkov-Trainer/blob/master/Installer/Installation.cs#L95

On my computer:
image

**Comment by sailro** [comment]
Just added more info to the prompt:

image

**Comment by solareon** [comment]
That's awesome. A definite improvement that should help. Maybe even one more line where it shows the latest supported version by grabbing from the repo?

**Comment by sailro** [comment]
Good idea, ideally getting all the dev-branches to know if we support a version or not (but sometimes we can even compile against an unknown version). Let me think about this.

**Comment by sailro** [comment]
image

**Comment by solareon** [comment]
I like it. Should help folks understand what one works/doesn't work.

**Pull request merged**
