### PR TITLE
Extract map logic and add fullscreen map feature

### PR DESCRIPTION
**Pull request by sailro**
Just a quick prototype.

Perhaps we'll need to disable all other OnGUI() when toggling the full map.

We can add ZoomIn/ZoomOut using the mouse/keys

We can reuse the teleport code we have in `FreeCamera` to quickly move to a location.

We can add a specific compass (we have one in the HUD -we need to use camera.transform for it as well istead of player.transform-)

### CODE REVIEW

**Comment by sailro** [comment]
We can have both `map` + `radar` (with minimap) working on the same time, but we need to enable `map` first then `radar`.

Playing with `camera.transparencySortMode = TransparencySortMode.CustomAxis` and `camera.transparencySortAxis` should do the trick (if we really want to be able to keep both, unsure about that)

https://docs.unity3d.com/ScriptReference/Camera-transparencySortAxis.html

**Comment by paulsnoops** [comment]
I'm using this trainer for SPTarkov because I wanted a minimap, so thank you!

Are the keys for opening the full screen map and zooming going to be able to be changed?

Also, could I make a request or two?

Instead of the white cross on the minimap could we have an option to have the centre be a circle to show where we are (same for the full map) and have compass bearings on each centre edge (NESW)? I can mock up an image if you like?

Could we also have the option to move the minimap too?

**Comment by paulsnoops** [comment]
Hmm I guess personally I'd rather it to rotate so maybe that part is a bad idea, unless you include an option for both?

**Comment by sailro** [comment]
> Maybe instead of radar minimap when on the fullview we just draw the locations of the enemy with no range cap?

Did that and refactored more. But I probably missed something:
- works perfectly in radar-mode.
- again weird position when moving the mouse in map-mode.

Also disabled extra GUI calls when using map-mode

**Comment by sailro** [comment]
> Got the full map working now just fixing the radar side.

Perfect!

**Pull request merged**
